### PR TITLE
Show compilation errors in compiled languages

### LINKED ISSUE #31: Bug: Judge for compiled languages if compilation fails
From @RubenVerg in the discord:

> compile errors in rust break the runner:
> ```
> error: Uncaught (in promise) NotFound: Failed to spawn '/tmp/output': No such file or directory (os error 2): No such file or directory (os error 2): No such file or directory (os error 2)
>     const process = command.spawn();
>                             ^
>     at spawnChildInner (ext:runtime/40_process.js:184:17)
>     at spawnChild (ext:runtime/40_process.js:208:10)
>     at Command.spawn (ext:runtime/40_process.js:483:12)
>     at run (file:///scripts/runner.ts:37:29)
>     at file:///scripts/runner.ts:71:54
>     at eventLoopTick (ext:core/01_core.js:175:7)
>     at async Code.on_run_callback [as onRunCallback] (file:///scripts/runner.ts:96:16)
>     at async Code.runCode (file:///scripts/runner-lib.ts:107:24)
>     at async default (data:text/typescript,export%20type%20Pass......lures()%3B%0D%0A%7D):141:16)
>     at async file:///scripts/runner.ts:106:22
> ```
> presumably it's trying to run an executable that doesn't exist because it didn't compile

### PR DESCRIPTION
**Pull request by Andriamanitra**
This might not be the absolute best way to show the compilation errors but at least they're shown to users now.

Also made compiled languages avoid recompilation of identical code, although I'm not completely sure if I successfully implemented that part.

Fixes #31

### CODE REVIEW

File: scripts/runner-lib.ts [hunk 1]
```diff
@@ -105,13 +109,23 @@ export class Code {
...
-                "error": result.stderr
+        let {stderr, stdout, compilationResult} = result;
+        const compilationFailed = compilationResult && compilationResult.exitStatus !== 0;
+        if (compilationFailed) {
+            stdout = compilationResult.stdout;
+            stderr = compilationResult.stderr;
+        }
+        const runDisplay: TestCase = new TestCase(
+            `Run #${++this.runs}`,
+            compilationFailed ? 'Fail' : 'Info',
```
Comment (mousetail) [inline scripts/runner-lib.ts]: I'd replace 'Fail' with 'Warning' here, so it doesn't effect "noFailures"

File: scripts/runner-lib.ts [hunk 2]
```diff
@@ -41,6 +41,10 @@ export type RunCodeResult = {
     exitStatus: number
 }
 
+export interface RunCompiledCodeResult extends RunCodeResult {
+    compilationResult: RunCodeResult | null
```
Comment (mousetail) [inline scripts/runner-lib.ts:45]: I generally prefer undefined to null when possible

File: scripts/runner.ts [hunk 3]
```diff
@@ -48,36 +48,49 @@ const run = async (args: string[], env: [string, string][], input: string): Prom
 }
 
 const compile_and_run_program = (() => {
-    const compiled_programs = {};
+    const compiled_programs: Record<string, string> = {};
 
-    const replaceTokens = ar => ar.map((e) => {
+    const replaceTokens = (ar: string[], outputLocation: string) => ar.map((e) => {
```
Comment (mousetail) [inline scripts/runner.ts:53]: I appreciate adding the type hints!
